2018-07-30 20:57:28,233 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 20:57:32,908 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 20:59:24,145 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\app\resourcesapi\Add_Expense_resource.py", line 39, in post
    MetdatasFromJSON = json_of_metadatas['json']
KeyError: 'json'
2018-07-30 21:01:24,588 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\app\resourcesapi\Add_Expense_resource.py", line 39, in post
    MetdatasFromJSON = json_of_metadatas['json']
KeyError: 'json'
2018-07-30 21:01:36,019 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 21:01:39,717 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 21:01:53,351 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 21:02:00,512 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 21:03:08,088 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 21:07:19,717 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 21:07:24,737 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 21:08:50,676 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-30 21:22:27,345 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\app\resourcesapi\Add_Expense_resource.py", line 39, in post
    MetdatasFromJSON = json_of_metadatas['jsondata']
KeyError: 'jsondata'
2018-08-02 18:47:00,596 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 18:47:05,733 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 19:08:37,275 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 19:16:00,448 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 19:44:11,362 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 20:53:25,165 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 20:53:28,834 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 20:53:49,678 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 83, in view
    self = view.view_class(*class_args, **class_kwargs)
TypeError: __init__() takes exactly 1 argument (2 given)
2018-08-02 20:55:08,447 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 20:55:59,053 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 20:56:02,661 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 20:57:47,940 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 21:02:45,673 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 21:02:48,687 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 21:08:44,766 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\app\resourcesapi\Add_Expense_resource.py", line 55, in post
    print files_data['filename']
TypeError: 'FileStorage' object has no attribute '__getitem__'
2018-08-02 21:22:38,217 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 21:22:41,553 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-02 21:23:27,750 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\app\resourcesapi\Add_Expense_resource.py", line 53, in post
    print files_data['filename']
TypeError: 'FileStorage' object has no attribute '__getitem__'
2018-08-02 21:23:43,517 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-03 15:19:48,480 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-03 16:05:22,217 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-03 16:05:26,869 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-03 16:10:22,463 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-03 16:22:37,765 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-03 16:22:40,440 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-08-03 16:31:41,240 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
