2018-07-27 18:16:09,966 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-27 18:16:11,881 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-27 18:27:35,697 ERROR: Exception on /apiV2/ExpenseRes [GET] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\app\resourcesapi\Add_Expense_resource.py", line 18, in get
    exptypes = Expenses.query.filter_by(u_id=current_user.id)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1642, in filter_by
    for key, value in kwargs.items()]
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'app.models.Expense_model.Expenses'>' has no property 'u_id'
2018-07-27 18:28:34,223 ERROR: Exception on /apiV2/ExpenseRes [GET] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\app\resourcesapi\Add_Expense_resource.py", line 18, in get
    exptypes = Expenses.query.filter_by(u_id=current_user.id)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1642, in filter_by
    for key, value in kwargs.items()]
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'app.models.Expense_model.Expenses'>' has no property 'u_id'
2018-07-27 18:29:14,022 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-27 18:29:48,342 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-27 18:30:03,542 ERROR: Exception on /apiV2/ExpenseRes [GET] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\app\resourcesapi\Add_Expense_resource.py", line 18, in get
    exptypes = Expenses.query.filter_by(u_id=current_user.id)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1642, in filter_by
    for key, value in kwargs.items()]
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'app.models.Expense_model.Expenses'>' has no property 'u_id'
2018-07-27 18:31:33,318 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-27 18:31:35,086 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-27 18:31:44,388 ERROR: Exception on /apiV2/ExpenseRes [GET] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 323, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 344, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\ProgramData\Anaconda2\Lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 442, in _iterencode
    o = _default(o)
  File "C:\ProgramData\Anaconda2\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <flask_sqlalchemy.BaseQuery object at 0x00000000067123C8> is not JSON serializable
2018-07-27 18:32:05,884 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-27 18:32:07,559 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-27 18:32:36,358 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:18:24,292 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:18:47,035 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:18:55,926 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:35:46,431 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:35:48,032 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:39:18,553 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:39:20,164 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:40:59,601 ERROR: Exception on /apiV2/ExpenseRes [POST] [in C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\venv\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\nijoshi\Desktop\E2ISANEW\app\resourcesapi\Add_Expense_resource.py", line 39, in post
    MetdatasFromJSON = json_of_metadatas['json']
KeyError: 'json'
2018-07-28 21:46:25,430 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:46:26,950 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:46:46,881 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
2018-07-28 21:46:48,398 INFO: E2ISA App startup [in C:\Users\nijoshi\Desktop\E2ISANEW\app\__init__.py:56]
